/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Application;

import java.awt.Font;
import javax.swing.JLabel;

/**
 *
 * @author overl
 */
public class WelcomePanel extends javax.swing.JPanel {
    private String name;
    private String userName;

    public JLabel getLogintext() {
        return logintext;
    }

    public void setLogintext(JLabel logintext) {
        this.logintext = logintext;
    }

    public JLabel getUserText() {
        return userText;
    }

    public void setUserText(JLabel userText) {
        this.userText = userText;
    }

    public JLabel getWelcomeText() {
        return welcomeText;
    }

    public void setWelcomeText(JLabel welcomeText) {
        this.welcomeText = welcomeText;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }
    /** Creates new form WelcomePanel */
    public WelcomePanel() {
        this.name = "Guest";
        initComponents();
        Thread t = new Thread(clock1);
        t.start();
    }
    public void updateText(){
        System.out.println(name+"\n"+userName);
        welcomeText.setText("Welcome "+name+" . Have a nice day!!");
        userText.setText(""+userName);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logintext = new javax.swing.JLabel();
        userText = new javax.swing.JLabel();
        clock1 = new Application.Clock();
        jPanel1 = new javax.swing.JPanel();
        welcomeText = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1600, 40));

        logintext.setFont(new Font(logintext.getFont().getName(), Font.PLAIN, 16));
        logintext.setText("login");
        logintext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logintextMouseClicked(evt);
            }
        });

        userText.setFont(new Font(userText.getFont().getName(), Font.PLAIN, 16));
        userText.setText(userName);

        welcomeText.setFont(new Font(welcomeText.getFont().getName(), Font.PLAIN, 16));
        welcomeText.setText("Welcome "+name+" . Have a nice day!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(welcomeText)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(welcomeText)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(clock1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1375, Short.MAX_VALUE)
                .addComponent(userText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logintext)
                .addGap(30, 30, 30))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userText)
                    .addComponent(logintext)
                    .addComponent(clock1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logintextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logintextMouseClicked
        // TODO add your handling code here:
        System.out.println("login : "+name+"\n"+userName);
        if(logintext.getText().equals("login")){
            new Signin(this).setVisible(true);
        }
        else if(logintext.getText().equals("logout")){
            this.userName = "";
            this.name = "Guest";
            this.logintext.setText("login");
            updateText();
        }
    }//GEN-LAST:event_logintextMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Application.Clock clock1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logintext;
    private javax.swing.JLabel userText;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables

}
